Controllers/Beauty2Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace BlogFashion.Controllers
{
    public class Beauty2Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/BeautyController.cs
using Microsoft.AspNetCore.Mvc;

namespace BlogFashion.Controllers
{
    public class BeautyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/FashionController.cs
using Microsoft.AspNetCore.Mvc;

namespace BlogFashion.Controllers
{
    public class FashionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HairController.cs
using Microsoft.AspNetCore.Mvc;

namespace BlogFashion.Controllers
{
    public class HairController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using BlogFashion.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogFashion.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LifeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BlogFashion.Controllers
{
    public class LifeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/NailController.cs
using Microsoft.AspNetCore.Mvc;

namespace BlogFashion.Controllers
{
    public class NailController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/RetinolController.cs
using Microsoft.AspNetCore.Mvc;

namespace BlogFashion.Controllers
{
    public class RetinolController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/StainController.cs
using Microsoft.AspNetCore.Mvc;

namespace BlogFashion.Controllers
{
    public class StainController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/Trend2Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace BlogFashion.Controllers
{
    public class Trend2Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/TrendController.cs
using Microsoft.AspNetCore.Mvc;

namespace BlogFashion.Controllers
{
    public class TrendController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Beauty/Index.cshtml
<main class="container">
    <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
        <div class="col-lg-8 px-0">
            <h1 class="display-4 fst-italic">Yeni güzellik ipuçları ve sırları</h1>
            <p class="lead my-3">Söz konusu güzellik olduğunda hepimizin mutlaka denediği ve test ettiği bir rutin olmuştur. Hepimizin daima bakım rutinimizden en iyi şekilde faydalanmak ve daha da güzel hissetmek için yardımcı olacak yeni güzellik sırlarının peşinde olduğunu söylememize bile gerek yok. İşte bizim favorimiz.</p>
            <p class="lead mb-0"><a asp-controller="Beauty2"asp-action="Index" class="text-body-emphasis fw-bold">Devamını oku...</a></p>
        </div>
    </div>

    <div class="row mb-2">
        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary-emphasis">Cilt Lekeleri</strong>
                    <h3 class="mb-0">İzleri sildirmenin tam zamanı</h3>
                    <div class="mb-1 text-body-secondary"></div>
                    <p class="card-text mb-auto">Yaz mevsiminde güneş ışınlarının daha dik açı ile daha uzun süre yeryüzüne ulaşması nedeniyle vücudumuz yoğun şekilde ultraviyole ışınlara maruz kalıyor..</p>
                    <a asp-controller="Stain" asp-action="Index" class="icon-link gap-1 icon-link-hover stretched-link">
                        Devamını okumak için tıkla
                    </a>
                </div>
                <div class="col-auto d-none d-lg-block">
                    <img class="d-block mx-auto mb-3" src="~/css/cilt3.jpg" alt="" width="209" height="299">

                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary-emphasis">RETİNOL</strong>
                    <h3 class="mb-0">RETİNOL NEDİR</h3>
                    <div class="mb-1 text-body-secondary"></div>
                    <p class="card-text mb-auto">Retinol bir A vitamini türevidir. Ciltteki kolajen üretimini arttırarak ince çizgi ve kırışıklıkları azaltmada rol oynar.</p>
                    <a asp-controller="Retinol" asp-action="Index" class="icon-link gap-1 icon-link-hover stretched-link">
                       Devamını okumak için tıkla
                    </a>
                </div>
                <div class="col-auto d-none d-lg-block">
                    <img class="d-block mx-auto mb-3" src="~/css/cilt2 (1).jpg" alt="" width="209" height="299">

                </div>
            </div>
        </div>
    </div>

    <div class="row g-5">
        <div class="col-md-8">
          

            <article class="blog-post">
                <h5 class="display-5 link-body-emphasis mb-1">
                  
                    Dermatologların Tavsiye Ettiği 5 Cilt Bakım Rutini
                </h5>

                <p>İşte danışman dermatolog Dr. Thivi Maruthappu'nun paylaştığı, muhtemelen şimdiden uygulamayı düşünmeniz gereken beş yeni yıl cilt kararı..</p>
                <hr>
                <h3>Cilt bakım rutininizi basitleştirin</h3>
                <p>Rutininizdeki farklı adımlarda hidroksi asitler ve retinol gibi fazla sayıda aktif içerik, cilt bariyerini bozabilir, kızarıklığı kötüleştirebilir ve hassasiyetleri artırabilir."</p>
               
                <h3>Cildiniz için 3 temel başlık</h3>
                <p>Çoğumuz yeni bir yıl başlarken önümüzdeki upuzun yıl için aldığımız kararların listesini yapma eğilimindeyizdir. Her gün meditasyon yapmak, farkındalık yaratmak ya da yeni bir beceri geliştirmek olsun amaç, yaşam kalitemizi arttırmaktır. Peki cildinizi nasıl daha iyi hale getirebilirsiniz? İşte danışman dermatolog Dr. Thivi Maruthappu'nun paylaştığı, muhtemelen şimdiden uygulamayı düşünmeniz gereken beş yeni yıl cilt kararı. 2024 yılı düzenlenmiş bir cilt vadediyor.</p>
                <ul>
                    <li>Cilt bakım rutininize yüksek kaliteli bir C vitamini ürünü ekleyin</li>
                    <li>Retinoidlerden vazgeçmeyin</li>
                    <li>Cildiniz için beslenme rutini oluşturun</li>
                </ul>
                <p>Listeye eklenecekler...</p>
                <ol>
                    <li>Sabahları C vitamini ve güneş koruyucu ile devam edin</li>
                    <li>Akşamları ise retinol ve nemlendirici düşünebilirsiniz.</li>
                    <li>Pigmentasyonla başa çıkmak için arbutin yardımcı olabilir</li>
                </ol>  
              
                <h2>Antioksidanlar</h2>
                <p>"Yılbaşı kutlamalarından sonra hepimiz biraz soluk ve yorgun görünebiliriz. Cildin daha derin katmanlarında çalışarak kolajeni ultraviyole ışınlardan ve kirlilik gibi çevresel faktörlerin zararlarından koruyan parlak renkli meyve ve sebzeleri tüketerek antioksidan alımınızı artırın. Unutmayın, meyve ve sebzeler ne kadar koyu renkli olursa, antioksidan içerikleri o kadar yüksek olur..</p>
                <h3>Farklı yağlar</h3>
                <p>Faydalı yağ alımınıza da dikkat edin. Somon gibi yağlı balıklar omega 3 ve protein için harika bir kaynaktır, ancak vegan veya vejetaryen iseniz, kaju fıstığı, keten tohumu yağlarını tercih edebilirsiniz ve günlük olarak omega 3 ile takviyeleri deneyebilirsiniz.  Her zamanki gibi, parlak bir cilt için nemlendirme çok önemlidir.  Suyunuza salatalık, limon veya nane ekleyerek daha ilgi çekici bir tat elde edebilirsiniz.".</p>
            </article>

            <article class="Süreklilik her şeydir">

                <p>“Cildimiz sürekliliği sever. Ürünlerinizi düzenli olarak değiştirmek cazip gelebilir, ancak işe yarayan basit bir rutine alışmak altın değerindedir. Günde iki kez cildinizi temizleyin; makyaj yapıyorsanız, ilk adım olarak bir temizleyici tonik veya balm ile çift temizlik yapın. Sabahları C vitamini ve güneş koruyucu ile devam edin, akşamları ise retinol ve nemlendirici düşünebilirsiniz. Cilt tipinize özel ihtiyaçlara bağlı olarak ek ürünler de kullanılabilinir. Örneğin, kızarıklığa yatkın ciltler için azelaik asit harika bir ek olabilir ve pigmentasyonla başa çıkmak için arbutin yardımcı olabilir.".</p>
          
                <h3>Güzellik Rutini Tablosu</h3>
                <p>Güzellik için önerilen rutinler:</p>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Ürün</th>
                            <th>Gece</th>
                            <th>Gündüz</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Maske</td>
                            <td>1</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>Tonik</td>
                            <td>1</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>GözAltı Kremi</td>
                            <td>1</td>
                            <td>0</td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td>Total</td>
                            <td>3</td>
                            <td>1</td>
                        </tr>
                    </tfoot>
                </table>

                <p>Ürünleri doğru sıralamayla uygulamadığınızda cilde nüfuz etmeleri zorlaşır, dolayısıyla içeriklerin faydalarını yeteri kadar göremezsiniz, yani ürünler etkisiz kalır. Dahası, bu durum bazı cilt problemlerine de zemin hazırlayabilir. .</p>
            </article>

            <article class="blog-post">
                <h2 class="display-5 link-body-emphasis mb-1">Gündüz ve gece bakımlarında nasıl farklılıklar olmalıdır?</h2>
             

                <p>Gün boyunca hava kirliliği, güneş ışığı, ısı değişimleri ve ekranlardan gelen mavi ışık gibi dış etkenlere maruz kalan cilt için ideal gündüz bakımı nemlendirmeye, önlemeye ve cildi çevresel etkenlere karşı korumaya yönelik olmalıdır..</p>
                <ul>
                    <li> Cildi onarmaya ve yenilemeye odaklanılmalıdır.</li>
                    <li> Lipitlerden ve proteinlerden zengin, yağ bazlı ürünler akşam bakımında tercih edilebilir.</li>
                    <li>Kimyasal peeling veya retinol gibi cildin güneş ışınlarına karşı hassasiyetini artıran içerikleri kullanmak için de doğru zaman yine gece bakımıdır.</li>
                </ul>
            </article>

            <nav class="blog-pagination" aria-label="Pagination">
                <a class="btn btn-outline-primary rounded-pill" href="#">Başa Dön</a>
            </nav>

        </div>

        <div class="col-md-4">
            <div class="position-sticky" style="top: 2rem;">
                <div class="p-4 mb-3 bg-body-tertiary rounded">
                    <h4 class="fst-italic">KUSURSUZ MAKYAJ</h4>
                    <p class="mb-0">Şeffaf fondötenler veya renkli nemlendiriciler tercih ederek minimalist bir yaklaşımı benimseyin ve cildinizin doğal ışıltısının parlamasına izin verin. .</p>
                </div>

                <div>
                    <h4 class="fst-italic">Bu yazılar ilginizi çekebilir</h4>
                    <ul class="list-unstyled">
                        <li>
                            <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" href="#">
                                <img src="~/css/resim1.jpg" class="" width="100%" height="96"  aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"></rect></>
                                <div class="col-lg-8">
                                    <h6 class="mb-0">Yeni güzellik ipuçları</h6>
                                    <small class="text-body-secondary">Ocak 15, 2024</small>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" href="#">
                                <img src="~/css/resim 2.jpg" class="" width="100%" height="96" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"></rect></>

                                <div class="col-lg-8">
                                    <h6 class="mb-0">Üstteki yazılara ulaşın.</h6>
                                    <small class="text-body-secondary">Ekim 14, 2023</small>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" href="#">
                                <img src="~/css/resim3.jpg" class="" width="100%" height="96" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"></rect></>

                                <div class="col-lg-8">
                                    <h6 class="mb-0">Üstteki yazılara ulaşın.</h6>
                                    <small class="text-body-secondary">Aralık 13, 2023</small>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>

             
               
            </div>
        </div>
    </div>

</main>

Views/Beauty2/Index.cshtml


<div class="card-body text-center">
    <h3 class="card-title">Güzellik İpuçları ve Sırları</h3>
    <p class="card-text">Hepimizin daima bakım rutinimizden en iyi şekilde faydalanmak ve daha da güzel hissetmek için yardımcı olacak yeni güzellik sırlarının peşinde olduğunu söylememize bile gerek yok..</p>
    <p>Söz konusu güzellik olduğunda hepimizin mutlaka denediği ve test ettiği bir rutin olmuştur..</p>
    <p>Peki,İşte bizim favorimiz, en pratik (ve faydalı) ipucu; bakalım repertuarınıza kaç tanesini ekleyeceksiniz?!</p>
</div>

<div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
        <div class="card h-100">
            <img src="~/css/Radiofrequência facial para remodelar o rosto.jpg" class="card-img-top" alt="...">
            <div class="card-body">
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card h-100">
            <img src="~/css/Beauty - Olga Blik.jpg" class="card-img-top" alt="...">
            <div class="card-body">
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card h-100">
            <img src="~/css/Natural Bridal Make Up (Shade 21 Pink Beige).jpg" class="card-img-top" alt="...">
            <div class="card-body">
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
</div>

    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">Vücut yağını deneyin.</h5>
            <p class="card-text">
                Yumuşacık bir cilt için en iyi güzellik sırlarından birisi vücut yağıdır:.
            </p>
            <p>En iyi cilt bakımı ve yumuşacık, ışıltılı mükemmel bir cilt için tüm zamanların en favori güzellik ipuçlarından birisi olmuştur. </p>
        </div>
    </div>
     
    <div class="px-4 py-5 my-5 text-center">
        <img src="~/css/VICHY AQUALIA THERMAL LIGHT.jpg" class=" text-center" alt=".." style="width:472px; height:557px ">

        <div class="card mb-3">
            <div class="card-body">
            <h5 class="card-title">Temel ürünleri el altında tutun..</h5>
                <p class="card-text">
                Son derece basit. Temel cilt bakım ürünlerini yatağınızın yakınında tutun, böylece yatmadan önce kullanmayı daima hatırlayacak ve etkili olmaları için ürünlere bolca zaman vermiş olacaksınız.
                </p>
                <p>En iyi cilt bakımı ve yumuşacık, ışıltılı mükemmel bir cilt için tüm zamanların en favori güzellik ipuçlarından birisi olmuştur. </p>
            </div>
        </div>
    </div>
        <div class="px-4 py-5 my-5 text-center">
            <img src="~/css/The Truth About Cleansing Oils.jpg" class=" text-center" alt=".." style="width:472px; height:557px ">

            <div class="card mb-3">
                <div class="card-body">
            <h5 class="card-title">Şişmiş göz kapaklarına buz uygulayın..</h5>
                    <p class="card-text">
                Sabahları uyandığınızda göz kapaklarınız şişmiş mi oluyor? Gazlı beze sarılı buz küpünü gözlerinizin çevresine hafif hafif vurun ve şişliklerin kısa sürede inmesine şahit olun.
                    </p>
            <p>Böylece evden iyice dinlenmiş bir görünümle çıkabilirsiniz. </p>
                </div>
            </div>
        </div>
            <div class="px-4 py-5 my-5 text-center">
                <img src="~/css/Anti-Aging Tips And Tricks _ StyleCraze.jpg" class=" text-center" alt=".." style="width:472px; height:557px ">

                <div class="card mb-3">
                    <div class="card-body">
            <h5 class="card-title">Özelliklerinizi ön plana çıkarın..</h5>
                        <p class="card-text">
                Mavi gözler için kahverengi, kahverengi gözler için mor vb. gibi gözlerinizin rengini ön plana çıkaracak tonlar seçin.
                        </p>
            <p>Tonların kontrast olması gözlerinizin güzelliğini ortaya çıkaracaktır. Zarifçe kullanın ve işte!: güzelliğiniz için (neredeyse) görünmez öz güveni kazanın! </p>
                    </div>
                </div>
            </div>
<nav class="blog-pagination" aria-label="Pagination">
    <a class="btn btn-outline-primary rounded-pill" href="#">Başa Dön</a>
</nav>

Views/Life/Index.cshtml


<div class="card-body text-center">
    <h3 class="card-title">Tüm Evinize Neşe Katacak Çocuk Odası Dekorasyonu Fikirleri</h3>
    <p class="card-text">Şimdi gözlerinizi kapatın ve çocukluğunuza doğru ufak bir yolculuğa çıkın..</p>
    <p>O yıllarda hayalinizdeki çocuk odasına sahip olabilmiş miydiniz? Bu soruya birçok kişinin yanıtını ne yazık ki hayır.</p>
    <p>Peki, şimdi hem kendi çocuğunuzun hem de içinizdeki çocuğun elinden tutarak rüya gibi bir dekorasyon yapmaya ne dersiniz? Çocuk odası için dekorasyon fikirlerimize göz atın!</p>
</div>
<div class="px-4 py-5 my-5 text-center">
    <img src="~/css/Bebek odası çocuk odası.jpg" class=" text-center" alt=".." style="width:472px; height:557px ">

    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">İşlevsel ve Eğlenceli Bir Çocuk Odası Dekorasyonu için Püf Noktalar</h5>
            <p class="card-text">
                Eşyaların boyutu: Çocuk odasındaki eşyaların her birinin çocuklar tarafından rahatlıkla kullanılabilecek boyutlarda olması gerekiyor.
            </p>
            <p>Alan özgürlüğü: 2023 yılı çocuk odası dekorasyonunda çocuklara daha özgür bir ortam yaratma fikri ön plana çıkıyor. Yani odanın ortasındaki alanı mümkün olduğunca boş bırakarak çocuklara oyun oynayacakları bir alan açabilirsiniz. </p>
            <p>Gelişimi destekleyen seçimler: Çocuk odasına alacağınız minik bir top havuzuyla çocuğun enerjisini atmasına, eğlenmesine ve en önemlisi fiziksel gelişimine destek olabilirsiniz.</p>
            <p>Çocuğun ilgi alanları: Çocuk odası için dekorasyon unsurlarını oda sahibinin ilgi alanlarına göre seçmeniz oldukça önemli. Rafları çocuğunuzun en sevdiği çizgi film karakterleriyle süsleyebilir veya duvar kağıdı seçiminde ilgi duyduğu alanlardan ilham alabilirsiniz.</p>
            <p>Kişisel alan ihtiyacı: Çocuklar kimi zaman yalnız kalacakları bir alana ihtiyaç duyabiliyor. Çocuğunuzu daha önce masanın altında veya perdenin arkasında kendi kendine oyun oynarken görmüş olabilirsiniz. Bu ihtiyacını gidermek için çocuğunuzun odasına minik bir oyun çadırı alabilirsiniz.</p>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Yılının En Sevilen Dekoratif Çocuk Odaları</h5>
            <p class="card-text">2024 çocuk odası dekorasyon trendlerinde çocukların odaya kendi kişisel dokunuşları ön plana çıkarken; sade ve birbiriyle uyumlu renklere, çocuğun gelişimini destekleyecek oyuncaklara, çocuğun kişisel alan ihtiyacına ve mobilyaların çocuk için işlevsel olmasına da önem veriliyor. .</p>
            <p>Ayrıca oyun saatlerinin çocuğun fiziksel ve zihinsel gelişimini büyük ölçüde etkilediği de artık bilinen bir gerçek</p>
            <p>Tabii ki çocuğun sanatsal aktivitelerini desteklemek için kolay silinebilir duvar kağıtları, parkeler ve halılar da son yıllarda oldukça popüler.</p>
        </div>
    </div>
    <img src="~/css/Hadi Çocuk Odası Tasarımlarını İnceleyelim.jpg" class="text-center" alt="..." style="width:472px; height:557px">

    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">Ebeveynler için Birbirinden Şık Çocuk Odası Dekorasyon Fikirleri.</h5>
            <p class="card-text">
                Yetişkinler ebeveynlik yolculuğunda her adımı büyük bir heyecanla atıyor.
            </p>
            <p>Nasıl ki çocuğun ilk adımı ve ilk kelimesi herkesi sevinçten havaya uçuruyorsa çocuğun ilk oda dekorasyonunu yaratmak da aynı derecede önem taşıyor.</p>
        </div>
    </div>
    <img src="~/css/Çocuk Odası Dekorasyon Fikirleri.jpg" class="text-center" alt="..." style="width:472px; height:457px">

</div>
<nav class="blog-pagination" aria-label="Pagination">
    <a class="btn btn-outline-primary rounded-pill" href="#">Başa Dön</a>
</nav>

Views/Nail/Index.cshtml

<div class="card text-center">
    <div class="card-header">
        2024’TE YÜKSELİŞE GEÇECEK 3 OJE RENGİ
    </div>
    <div class="card-body">
        <h5 class="card-title"> Elektrik Mavisi</h5>
        <p class="card-text">
            Mavinin en dikkat çekici tonlarından biri olan elektrik mavisi, canlı renkleri sevenler için birebir. Yaz ya da kış fark etmeden 2024 yılında tırnaklarınıza hem zarif hem de iddialı bir görünüm kazandırmanızı mümkün kılarken, uzun ve kısa tırnakta da ayrı bir etkileyiciliğe sahip.
        </p>
        <h5 class="card-title"> Şeftali Tonlar</h5>
        <p class="card-text">
            Pantone 2024’ün rengini Peach Fuzz yani Şeftali Tüyü olarak duyurduğundan beri bu tatlı renge duyulan ilgi de artmış durumda. Haliyle tırnakları da süslemesi kaçınılmaz. Şeftali renginin bu sıcak ve sakin tonu, sade ve şık bir manikür için ilkbahar ve yaz ayları için ideal.

        </p>
        <h5 class="card-title"> Metalik Tonlar</h5>
        <p class="card-text">
            Mavinin en dikkat çekici tonlarından biri olan elektrik mavisi, canlı renkleri sevenler için birebir. Yaz ya da kış fark etmeden 2024 yılında tırnaklarınıza hem zarif hem de iddialı bir görünüm kazandırmanızı mümkün kılarken, uzun ve kısa tırnakta da ayrı bir etkileyiciliğe sahip.
        </p>
        
    </div>
 
</div>

<a asp-controller="Home" asp-action="Index">Anasayfaya Dön</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogFashion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogFashion.styles.css" asp-append-version="true" />
</head>
<body>
    <nav class="navbar navbar-dark bg-info ">
    <div class="container">
        <header class="d-flex justify-content-center py-2">
                <ul class="nav justify-content-center">

                <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">HOME</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="Fashion" asp-action="Index">MODA</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="Beauty" asp-action="Index">GÜZELLİK</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="Life" asp-action="Index">YAŞAM</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="Trend" asp-action="Index">TREND</a></li>
            </ul>
        </header>
    </div>
    </nav>
    <br />
   
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
           Yeliz Taçgın - 2024 - BlogFashion -
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>